AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  backlog_to_slack_for_pycharm

  Sample SAM Template for backlog_to_slack_for_pycharm

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 300

Resources:
  SendtoSlackFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: backlog_to_slack_for_pycharm/
      Handler: app.lambda_handler
      Runtime: python3.8
      Events:
        Schedule1:
          Type: Schedule
          Properties:
            Schedule: cron(0 0 ? * MON-FRI *)

Outputs:
  SendtoSlackFunction:
    Description: "SendtoSlack Lambda Function ARN"
    Value: !GetAtt SendtoSlackFunction.Arn
  SendtoSlackFunctionIamRole:
    Description: "Implicit IAM Role created for SendtoSlack function"
    Value: !GetAtt SendtoSlackFunctionRole.Arn
